### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by DusKing1** [gyroflow/flowshutter#2]
- [ ] Add two CRSF "trigger" packets - make the FC arm/disarm
- [ ] Add button detector - pressed/released
- [ ] Add sony multiport protocol support - flowshutter can be registered as sony remote
- [ ] Improve UI
- [ ] Provide an easy-to-go DIY board - then hook up an betaflight FC
- [ ] Add support for "audio sync" - put sync signal on both camera's audio track and on FC's throttle (maybe roll pitch or yaw) channel
- [ ] Add "EEPROM" and "menu" for changing some settings and saving that after powering off
- [ ] Improve "menu" logic and UI
- [ ] Add support for triggering record via voltage change

**Comment by CptCurk** [comment]
hello ! 
I'm almost on the way to buy a Neutron Flowshutter. 
But I'm using a fuji X-T3. How could I know if I can make it work with this camera ? 
Thank you !
